export const list = [
  {
    owner: 'Fayiz',
    name: 'MERN',
    vendor_name: 'siraj',
    code: '65276528',
    active: true,
    catogery: 'none',
  },
  {
    owner: 'Abhi',
    name: 'MEAN',
    vendor_name: 'siraj',
    code: '92276528',
    active: true,
    catogery: 'none',
  },
  {
    owner: 'Rahul',
    name: 'Django',
    vendor_name: 'siraj',
    code: '82276528',
    active: false,
    catogery: 'none',
  },
  {
    owner: 'John',
    name: 'React',
    vendor_name: 'siraj',
    code: '34276528',
    active: true,
    catogery: 'none',
  },
  {
    owner: 'Sam',
    name: 'Python',
    vendor_name: 'siraj',
    code: '12276528',
    active: false,
    catogery: 'none',
  },
  {
    owner: 'Simon',
    name: 'DSA',
    vendor_name: 'siraj',
    code: '64876528',
    active: false,
    catogery: 'none',
  },
];
